### ISSUE TITLE
Chapter 11 Incorrect Gender Counterfactual

### ISSUE THREAD

**Issue by Dekermanjian** [dustinstansbury/statistical-rethinking-2023#1]
There is an issue with the "total_effect_gender_model" in the chapter 11 notebook. The problem arises because the coord for "GENDER" and the data container for "GENDER_ID" use the same name "gender". To fix the issue just change one of the names in my case I just changed the following line:
```
gender = pm.MutableData('gender', GENDER_ID)
```

to: 
```
gender = pm.MutableData('gender_id', GENDER_ID)
```

**Comment by dustinstansbury** [comment]
Good catch, thanks @Dekermanjian! Fixed in [e2b3745](https://github.com/dustinstansbury/statistical-rethinking-2023/commit/e2b37452049c9d5bac05c4ea4edb02116f1f01a7).
